### ISSUE TITLE
Add harpoon to the projects list

### ISSUE THREAD

**Issue by alegrey91** [zoidyzoidzoid/awesome-ebpf#108]
Hi,

I'm currently developing this tool to trace system calls from user-defined functions:
https://github.com/alegrey91/harpoon

I'm wondering if it can be added to the list. This is far to be a great project as the others in the list, but if you would add it, I'll be happy to provide the PR for this.

**Comment by qmonnet** [comment]
Looks like a nice project! Would you be willing to submit a PR?

**Comment by alegrey91** [comment]
> Looks like a nice project! Would you be willing to submit a PR?

Sure, thanks ;)
